import type { Ruolo, StatoContenuto, TipoCommento, TipoContenuto } from './tipi';

/** Testi del portale della redazione. */
export const TESTI_REDAZIONE = {
  marchio: 'Redazione',
  sottomarchio: 'Palestra social',

  accesso: {
    titolo: 'Entra in redazione',
    sottotitolo: 'Qui pubblichi i post e le storie che fai col generatore, come su Instagram. Chi coordina vede tutto e ti lascia correzioni e consigli.',
    nome: 'Il tuo nome',
    nomeSegnaposto: 'Nome e cognome',
    nomeAiuto: 'Usa sempre lo stesso: è così che ritrovi i tuoi contenuti.',
    codice: 'Codice della redazione',
    codiceAiuto: 'Te lo dà chi coordina.',
    entra: 'Entra',
    entrando: 'Entro…',
    nonConfigurato: 'Il portale non è ancora attivo: mancano i codici di accesso sul server (REDAZIONE_CODICE e REDAZIONE_CODICE_REVISORI).',
    riservato: 'Area riservata alla redazione. I contenuti restano qui e non vengono pubblicati da nessuna parte.',
  },

  ruolo: { redattore: 'Redattore', revisore: 'Revisore' } satisfies Record<Ruolo, string>,
  esci: 'Esci',

  schede: {
    feed: 'Feed',
    profilo: 'Il mio profilo',
    revisione: 'Da rivedere',
    squadra: 'Squadra',
  },

  nuovo: 'Nuovo',
  tipo: { post: 'Post', storia: 'Storia' } satisfies Record<TipoContenuto, string>,
  piuPost: '+ Post',
  piuStoria: '+ Storia',
  miniatura: (tipo: TipoContenuto, autore: string) => `Apri ${tipo === 'post' ? 'il post' : 'la storia'} di ${autore}`,
  nuovoPost: 'Nuovo post',
  nuovaStoria: 'Nuova storia',
  laTuaStoria: 'La tua storia',

  stato: {
    da_rivedere: 'Da rivedere',
    da_correggere: 'Da correggere',
    approvato: 'Approvato',
  } satisfies Record<StatoContenuto, string>,
  coloreStato: {
    da_rivedere: '#60A5FA',
    da_correggere: '#F59E0B',
    approvato: '#22C55E',
  } satisfies Record<StatoContenuto, string>,

  tipoCommento: {
    correzione: 'Correzione',
    consiglio: 'Consiglio',
    complimento: 'Bravo!',
    risposta: 'Risposta',
  } satisfies Record<TipoCommento, string>,
  coloreCommento: {
    correzione: '#F59E0B',
    consiglio: '#60A5FA',
    complimento: '#22C55E',
    risposta: '#A3A3A3',
  } satisfies Record<TipoCommento, string>,

  feed: {
    vuoto: 'Ancora nessun post. Rompi il ghiaccio!',
    errore: 'Non riesco a caricare i contenuti.',
    riprova: 'Riprova',
    aggiorna: 'Aggiorna',
    caricamento: 'Carico i contenuti…',
    apri: 'Apri',
    commenti: (n: number) => (n === 1 ? '1 commento' : `${n} commenti`),
    versione: (n: number) => `Versione ${n}`,
    altro: 'altro',
  },

  profilo: {
    post: 'post',
    storie: 'storie',
    contaStorie: (n: number) => (n === 1 ? 'storia' : 'storie'),
    contaApprovati: (n: number) => (n === 1 ? 'approvato' : 'approvati'),
    daCorreggere: 'da correggere',
    vuotoPost: 'Nessun post per ora.',
    vuotoStorie: 'Nessuna storia per ora.',
    indietro: '← Torna alla squadra',
    tuoi: 'I tuoi contenuti',
    generatore: 'Apri il generatore ↗',
    generatoreAiuto: 'Card e storie si fanno lì: scaricale e pubblicale qui.',
    di: (nome: string) => `I contenuti di ${nome}`,
    avvisoCorrezioni: (n: number) =>
      n === 1 ? 'Hai 1 contenuto con correzioni da fare.' : `Hai ${n} contenuti con correzioni da fare.`,
  },

  revisione: {
    titolo: 'Coda delle correzioni',
    spiegazione: 'Prima chi aspetta da più tempo. Ogni nuova versione di un contenuto torna qui.',
    vuota: 'Tutto rivisto. Ottimo lavoro!',
    inAttesaDa: (quando: string) => `inviato ${quando}`,
  },

  squadra: {
    titolo: 'La squadra',
    spiegazione: 'Quanto pubblica ognuno e a che punto sono le correzioni.',
    vuota: 'Nessuno ha ancora pubblicato.',
    colonne: {
      persona: 'Persona',
      settimana: 'Ultimi 7 giorni',
      post: 'Post',
      storie: 'Storie',
      daRivedere: 'Da rivedere',
      daCorreggere: 'Da correggere',
      approvati: 'Approvati',
      ultimo: 'Ultimo invio',
    },
    apri: (nome: string) => `Apri i contenuti di ${nome}`,
  },

  dettaglio: {
    chiudi: 'Chiudi',
    versioni: 'Versioni',
    versioneCorta: (n: number) => `v${n}`,
    correzioni: 'Correzioni e consigli',
    nessunCommento: 'Ancora nessun commento.',
    commentiPrivati: 'Le correzioni le vedono solo l\'autore e chi coordina.',
    suVersione: (n: number) => `sulla versione ${n}`,
    correggi: 'Correggi: pubblica una nuova versione',
    elimina: 'Elimina',
    confermaElimina: 'Eliminare definitivamente? Spariscono anche versioni e commenti.',
    scriviCommento: 'Scrivi una correzione o un consiglio',
    scriviRisposta: 'Rispondi',
    segnapostoRevisore: 'Cosa funziona, cosa cambiare, come riscriverlo…',
    segnapostoAutore: 'Una domanda o un chiarimento per chi ti corregge',
    tipo: 'Tipo di commento',
    invia: 'Invia',
    inviaECorreggi: 'Invia e chiedi correzione',
    approva: 'Approva',
    riapri: 'Rimetti da rivedere',
    invio: 'Invio…',
    errore: 'Non sono riuscito a salvare, riprova.',
  },

  compositore: {
    titoloPost: 'Nuovo post',
    titoloStoria: 'Nuova storia',
    titoloVersione: (n: number) => `Nuova versione (v${n})`,
    annulla: 'Annulla',
    pubblica: 'Pubblica',
    pubblicaVersione: 'Pubblica la nuova versione',
    caricamento: (fatte: number, totale: number) => `Carico le immagini (${fatte}/${totale})…`,
    salvataggio: 'Pubblico…',
    dalGeneratorePost: 'Fai le card nel generatore, scaricale e caricale qui con il copy.',
    dalGeneratoreStoria: 'Fai la storia nel generatore, scaricala e caricala qui.',
    apriGeneratore: 'Apri il generatore ↗',
    foto: 'Card',
    fotoPost: 'Card del post (fino a 10, la prima è la copertina)',
    fotoStoria: 'Immagine della storia (9:16)',
    aggiungiFoto: 'Carica card',
    caricaStoria: 'Carica storia',
    cambiaFoto: 'Cambia immagine',
    togliFoto: 'Togli',
    spostaPrima: 'Sposta prima',
    spostaDopo: 'Sposta dopo',
    didascalia: 'Copy',
    didascaliaSegnaposto: 'Scrivi il copy: gancio nella prima riga, poi il contenuto, poi gli hashtag.',
    caratteri: (n: number, max: number) => `${n}/${max} caratteri`,
    hashtag: (n: number, max: number) => `${n}/${max} hashtag`,
    anteprima: 'Anteprima',
    erroreFoto: 'Questa immagine non si apre: prova con un JPEG o un PNG.',
    erroreInvio: 'Pubblicazione non riuscita, riprova.',
  },

  storie: {
    chiudi: 'Chiudi le storie',
    precedente: 'Storia precedente',
    successiva: 'Storia successiva',
    pausa: 'Metti in pausa',
    riprendi: 'Riprendi',
    apri: 'Apri correzioni',
    di: (nome: string, n: number) => `Storie di ${nome}, ${n} ${n === 1 ? 'storia' : 'storie'}`,
    elenco: 'Storie delle ultime 24 ore',
  },
};
